### ISSUE TITLE
Authorization failed for 127.0.0.1 on GET /loadtracks

### ISSUE THREAD

**Issue by Atm85** [Yucked/Victoria#55]
I get this error when trying to use different passwords other then the default "youshallnotpass"
```
Authorization failed for 127.0.0.1 on GET /loadtracks
```
```yml
#application.yml
lavalink:
  server:
    password: "newPassword"
```
```csharp
// MusicService.cs
await _lavaSocketClient.StartAsync(_client, new Configuration
{
    Host = "127.0.0.1",
    Password = "newPassword"
});
```
